### ISSUE TITLE
please add in preconditions

### ISSUE THREAD

**Issue by z4q** [jonitram/pokebreederbot#1]
1.make sure have a good weather. 

if rainy or storm got problem with the automation.

**Comment by z4q** [comment]
i usually change the date to yesterday or tomorrow.

**Comment by jonitram** [comment]
thanks for the heads up. i did not know that rainy / stormy weather breaks the automation. i'll look into a fix if it's possible, but for now i'll just add good weather as a necessity to the preconditions.
